name: Kør test på API

on:
  push:
    branches: [ "develop" ]
    
jobs:
  
  Build_and_test:
    name: Build solution and test API
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.x'
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test with the dotnet CLI
      run: dotnet test --no-build